webtalk_init -webtalk_dir C:/Users/rodi3/Documents/EE2026 Project/mahjong_game_logic/ee2026_project/MODS.sim/sim_1/behav/xsim/xsim.dir/test_top_student_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Oct 17 12:41:28 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "056971a6-82f8-4369-a001-16854dc79724" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "63befdab578c422a95f612615b25a4cc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i7-1360P" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2611 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "7" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "106 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "6 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "50" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "7" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.25_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "53708_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2001187157 -regid "" -xml C:/Users/rodi3/Documents/EE2026 Project/mahjong_game_logic/ee2026_project/MODS.sim/sim_1/behav/xsim/xsim.dir/test_top_student_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/rodi3/Documents/EE2026 Project/mahjong_game_logic/ee2026_project/MODS.sim/sim_1/behav/xsim/xsim.dir/test_top_student_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/rodi3/Documents/EE2026 Project/mahjong_game_logic/ee2026_project/MODS.sim/sim_1/behav/xsim/xsim.dir/test_top_student_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
